### ISSUE TITLE
Cannot instantiate the custom serializer/deserializer

### ISSUE THREAD

**Issue by freddyboucher** [nmorel/gwt-jackson#117]
Hi,

I'm implementing a new gwt-jackson extension for **Objectify**.
This is currently where I am: https://github.com/freddyboucher/gwt-jackson/commit/8a58beb31ba344eaf2eb1d52d97a355bc376e880

The server-side Jackson Module is done but I'm facing an issue with the client-side implementation.

When I run the [GwtJacksonTestCase](https://github.com/freddyboucher/gwt-jackson/blob/objectify/extensions/objectify/src/test/java/com/github/nmorel/gwtjackson/objectify/client/GwtJacksonTestCase.java), I get the following stacktrace:

> Rebinding com.github.nmorel.gwtjackson.objectify.client.GwtJacksonTestCase.KeyMapper
   Invoking generator com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator
      [ERROR] Cannot instantiate the custom serializer/deserializer com.github.nmorel.gwtjackson.objectify.client.KeySerializer. Check the page https://github.com/nmorel/gwt-jackson/wiki/Custom-serializers-and-deserializers for more details.
[ERROR] Deferred binding failed for 'com.github.nmorel.gwtjackson.objectify.client.GwtJacksonTestCase.KeyMapper'; expect subsequent failures
> 
> java.lang.ExceptionInInitializerError
	at com.github.nmorel.gwtjackson.objectify.client.GwtJacksonTestCase.testKey1(GwtJacksonTestCase.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.junit.client.impl.GWTTestAccessor.invoke(GWTTestAccessor.java:39)
	at com.google.gwt.junit.client.impl.GWTRunner.executeTestMethod(GWTRunner.java:226)
	at com.google.gwt.junit.client.GWTTestCase.doRunTest(GWTTestCase.java:157)
	at junit.framework.TestCase.runTest(TestCase.java:59)
	at com.google.gwt.junit.client.GWTTestCase.runBare(GWTTestCase.java:151)
	at com.google.gwt.junit.client.GWTTestCase.__doRunTest(GWTTestCase.java:115)
	at com.google.gwt.junit.client.impl.GWTRunner.runTest(GWTRunner.java:302)
	at com.google.gwt.junit.client.impl.GWTRunner.doRunTest(GWTRunner.java:235)
	at com.google.gwt.junit.client.impl.GWTRunner.access$9(GWTRunner.java:229)
	at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:106)
	at com.google.gwt.junit.client.impl.GWTRunner$InitialResponseListener.onSuccess(GWTRunner.java:61)
	at com.google.gwt.junit.client.impl.GWTRunner$InitialResponseListener.onSuccess(GWTRunner.java:1)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
	at com.google.gwt.http.client.Request.fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Deferred binding failed for 'com.github.nmorel.gwtjackson.objectify.client.GwtJacksonTestCase$KeyMapper' (did you forget to inherit a required module?)
	at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:53)
	at com.google.gwt.core.shared.GWT.createImpl(GWT.java:83)
	at com.google.gwt.core.client.GWT.create(GWT.java:86)
	at com.github.nmorel.gwtjackson.objectify.client.GwtJacksonTestCase$KeyMapper.<clinit>(GwtJacksonTestCase.java:62)
	... 46 more
Caused by: com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.github.nmorel.gwtjackson.rebind.RebindConfiguration.getInstance(RebindConfiguration.java:408)
	at com.github.nmorel.gwtjackson.rebind.RebindConfiguration.addMappers(RebindConfiguration.java:312)
	at com.github.nmorel.gwtjackson.rebind.RebindConfiguration.<init>(RebindConfiguration.java:228)
	at com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator.generate(ObjectMapperGenerator.java:38)
	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:760)
	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
	at com.google.gwt.dev.shell.ShellModuleSpaceHost.rebind(ShellModuleSpaceHost.java:152)
	at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:613)
	at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:483)
	at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:49)
	... 49 more

The issue comes from my [KeySerializer](https://github.com/freddyboucher/gwt-jackson/blob/objectify/extensions/objectify/src/main/java/com/github/nmorel/gwtjackson/objectify/client/KeySerializer.java) and [KeyDeserializer](https://github.com/freddyboucher/gwt-jackson/blob/objectify/extensions/objectify/src/main/java/com/github/nmorel/gwtjackson/objectify/client/KeyDeserializer.java).

If I don't register these classes in my [ObjectifyConfiguration](https://github.com/freddyboucher/gwt-jackson/blob/objectify/extensions/objectify/src/main/java/com/github/nmorel/gwtjackson/objectify/client/ObjectifyConfiguration.java), I don't get this stacktrace anymore but of course the tests fail.
```java
public class ObjectifyConfiguration extends AbstractConfiguration {

    @Override
    protected void configure() {
        type( com.google.appengine.api.datastore.Key.class ).serializer( RawKeySerializer.class ).deserializer( RawKeyDeserializer.class );
//        type( Key.class ).serializer( KeySerializer.class ).deserializer( KeyDeserializer.class );
    }
}
```

Any clue please?

And by any chance,  is anyone interested by this Objectify extension and should I merge it in the main repo as soon as it's finished?

Thanks

**Comment by nmorel** [comment]
The generator doesn't find a suitable constructor for your serializer and deserializer.
`Key` is a generic type and the generator requires a constructor or static method accepting a parameter for each type parameter. 

You can follow [this guide](https://github.com/nmorel/gwt-jackson/wiki/Custom-serializers-and-deserializers#generic-types).

After that, I added a type in your tests and it works.
Here is the modified version.
I don't know what kind of type you are expecting in Key ? 
If the type is not used, you could just remove it in the super source or tweak the RebindConfiguration class to accept a constructor without parameter.

```java
public class KeyDeserializer<T> extends JsonDeserializer<Key<T>> {

    public static <T> KeyDeserializer<T> newInstance( JsonDeserializer<T> deserializer ) {
        return new KeyDeserializer<T>( deserializer );
    }

    private final JsonDeserializer<T> deserializer;

    private KeyDeserializer( JsonDeserializer<T> deserializer ) {
        if ( null == deserializer ) {
            throw new IllegalArgumentException( "deserializer can't be null" );
        }
        this.deserializer = deserializer;
    }

    @Override
    protected Key<T> doDeserialize( JsonReader reader, JsonDeserializationContext ctx, JsonDeserializerParameters params ) {
        reader.beginObject();
        if ( !KeyConstant.RAW.equals( reader.nextName() ) ) {
            throw ctx.traceError( "Missing " + KeyConstant.RAW + " property.", reader );
        }
        com.google.appengine.api.datastore.Key raw = RawKeyDeserializer.getInstance().deserialize( reader, ctx, params );
        reader.endObject();
        return Key.create( raw );
    }
}
```

```java
public class KeySerializer<T> extends JsonSerializer<Key<T>> {

    public static <T> KeySerializer<T> newInstance( JsonSerializer<T> serializer ) {
        return new KeySerializer<T>( serializer );
    }

    private final JsonSerializer<T> serializer;

    private KeySerializer( JsonSerializer<T> serializer ) {
        if ( null == serializer ) {
            throw new IllegalArgumentException( "serializer cannot be null" );
        }
        this.serializer = serializer;
    }

    @Override
    protected void doSerialize( JsonWriter writer, Key<T> key, JsonSerializationContext ctx, JsonSerializerParameters params ) {
        writer.beginObject();
        writer.name( KeyConstant.RAW );
        RawKeySerializer.getInstance().serialize( writer, key.getRaw(), ctx, params );
        writer.endObject();
    }
}
```

```java
    public interface KeyMapper extends ObjectMapper<Key<Object>> {

        KeyMapper INSTANCE = GWT.create( KeyMapper.class );
    }
```

**Comment by freddyboucher** [comment]
Waou!! thanks a lot!

**Comment by angryagr** [comment]
Hi, could you help me? What is the  RawKeySerializer here? How to implement it?
Thanks a lot.

**Comment by freddyboucher** [comment]
@angryagr 
RawKeySerializer is necessary for the [objectify extension](https://github.com/nmorel/gwt-jackson/tree/master/extensions/objectify)
What is your issue?

**Comment by angryagr** [comment]
So, my problem: I have RestyGwt client and Spring mvc Server. I want to achieve their communication.
But RestyGwt cant property serialise the types.
**Here is my code:**

**generic Action interface and its Implementation:**
`@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "class")
public interface Action<IxR extends Result> extends Serializable {}`

**and its Implementation:**
`@JsonTypeName("MyUserActionDto")
public class MyUserActionDto implements Action<MyUserResultDto> {
	private String id;
	private String name;
	private String surname;
	private String eMail;
	private String city;

	public MyUserActionDto() {
	}

	@JsonCreator
	public MyUserActionDto(@JsonProperty("userName") String userName, @JsonProperty("userSurname") String userSurname,
			@JsonProperty("userEmail") String userEmail, @JsonProperty("userCity") String userCity) {
		this.name = userName;
		this.surname = userSurname;
		this.eMail = userEmail;
		this.city = userCity;
	}`

**my client:**
`@Path("/hi")
public interface DispatchRestClient extends RestService {
	@POST
	@Path("/user")
	public <R extends Result> void execute(@FormParam(value="action")Action<R> action, MethodCallback<R> callback) throws DispatchException;`
my entrypoint:
`Defaults.setServiceRoot(GWT.getHostPageBaseURL());
		final DispatchRestClient service = GWT.create(DispatchRestClient.class);
checkDatabutton.addClickHandler(new ClickHandler() {

			public void onClick(ClickEvent event) {
				final Action<MyUserResultDto> myUserActionDto = new MyUserActionDto(inputTxtName.getText(), inputTxtSurname.getText(),
						inputTxtEmail.getText(), citiesListBox.getSelectedItemText());
				service.execute(myUserActionDto, new MethodCallback<MyUserResultDto>() {

					@Override
					public void onFailure(Method method, Throwable exception) {
						Window.alert("POST onFailure");
					}

					@Override
					public void onSuccess(Method method, MyUserResultDto result) {
						MyUserResultDto myUserResult = (MyUserResultDto) result;
						List<MyUserDto> users = (List<MyUserDto>)myUserResult.getMyUserList();
						DataSource datasource = new DataSource(users);
						table.setInput(datasource);
					}
				});
			}
		});`

I try to write ActionJsonSerializer:
`public final class ActionJsonSerializer<R extends Result> extends JsonSerializer<Action<R>> {


	public static <R extends Result> ActionJsonSerializer<R> newInstance(JsonSerializer<R> serializer) {
		return new ActionJsonSerializer<R>(serializer);
	}

	private final JsonSerializer<R> serializer;

	private ActionJsonSerializer(JsonSerializer<R> serializer) {
		if (null == serializer) {
			throw new IllegalArgumentException("serializer cannot be null");
		}
		this.serializer = serializer;
	}

	@Override
	protected void doSerialize(JsonWriter writer, Action<R> value, JsonSerializationContext ctx,
			JsonSerializerParameters params) {
		writer.beginObject();????`

**Comment by freddyboucher** [comment]
@angryagr 
Ok I see...
I added a commit to illustrate your issue: https://github.com/freddyboucher/gwt-storage-objectify/commit/131497e23684fe836301f372aceee3c3ab6f9745

But if you checkout this commit https://github.com/freddyboucher/gwt-storage-objectify/commit/bd98686b7ce95a1fe771492a09d84cc72783f92d everything is working fine

**Comment by angryagr** [comment]
Thank you very much =)))) Its what I needed=))))

Am Di., 18. Sep. 2018 um 18:30 Uhr schrieb Freddy Boucher <
notifications@github.com>:
